#!/usr/bin/python3
from sys import argv
from math import sqrt


def factorize():
    with open(argv[1], "r", encoding="utf-8") as file:
        for line in file:
            number = int(line)
            print(f"{number}=", end="")
            if number % 2 == 0:
                print(f"{number//2}*2")
                continue
            for i in range(3, int(sqrt(number)) + 1, 2):
                if number % i == 0:
                    print(f"{number//i}*{i}")
                    break
            if number % i != 0:
                print(f"{number}={number}*1")


factorize()
